# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Justdoit < Formula
  desc "Time-blocking CLI for Google Tasks and Google Calendar."
  homepage "https://github.com/antoniolg/justdoit"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/antoniolg/justdoit/releases/download/v0.1.2/justdoit_0.1.2_darwin_amd64.tar.gz"
      sha256 "2050f3d6af0ba6f8deccf1269b188bb2b3f892e594f0e5294c46ea636b419491"

      def install
        bin.install "justdoit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/antoniolg/justdoit/releases/download/v0.1.2/justdoit_0.1.2_darwin_arm64.tar.gz"
      sha256 "00cd68b15de8765f276bca71310f8c1bb84fcedd55156384236155c75111d9b6"

      def install
        bin.install "justdoit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniolg/justdoit/releases/download/v0.1.2/justdoit_0.1.2_linux_amd64.tar.gz"
      sha256 "b2cec5c959d9811c4ad6b86e041f81300556edf824be0118756a71786a9762e4"
      def install
        bin.install "justdoit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniolg/justdoit/releases/download/v0.1.2/justdoit_0.1.2_linux_arm64.tar.gz"
      sha256 "33a3cab94d9dbf9fcb8810c072182276508277650551fee3e3c4562bf8c2b595"
      def install
        bin.install "justdoit"
      end
    end
  end

  test do
    system "#{bin}/justdoit", "--help"
  end
end
