# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Justdoit < Formula
  desc "Time-blocking CLI for Google Tasks and Google Calendar."
  homepage "https://github.com/antoniolg/justdoit"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/antoniolg/justdoit/releases/download/v0.1.0/justdoit_0.1.0_darwin_amd64.tar.gz"
      sha256 "63f22771803981587724499b5bed476aa6a38a6cf5b5721b8517579e5f6f5aa6"

      def install
        bin.install "justdoit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/antoniolg/justdoit/releases/download/v0.1.0/justdoit_0.1.0_darwin_arm64.tar.gz"
      sha256 "4728f6f21960919df71ae9cd5022e0a323f63f83ab999d3ba7ab6c6abd7576da"

      def install
        bin.install "justdoit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniolg/justdoit/releases/download/v0.1.0/justdoit_0.1.0_linux_amd64.tar.gz"
      sha256 "cdaf8e9662bdc49a64dca1ac0c4d6eef845e452a449a38e081c4cd436cd95ec7"
      def install
        bin.install "justdoit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniolg/justdoit/releases/download/v0.1.0/justdoit_0.1.0_linux_arm64.tar.gz"
      sha256 "7f8fe2e16a2ed0b2d585726102ff3dd4d951a42a0a63f8a1a9d8afdb7f24fd03"
      def install
        bin.install "justdoit"
      end
    end
  end

  test do
    system "#{bin}/justdoit", "--help"
  end
end
