# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class ListmonkCli < Formula
  desc "CLI for Listmonk campaigns, lists, subscribers, templates, and transactional emails."
  homepage "https://github.com/antoniolg/listmonk-cli"
  url "https://github.com/antoniolg/listmonk-cli/releases/download/v0.1.0/listmonk-cli_0.1.0.tar.gz"
  sha256 "31bb09b9968e34b310b2c7ce0d47f18d5cae8ba3815b2230ce6bef5789468618"
  version "0.1.0"

  depends_on "node"

  def install
    libexec.install Dir["*"]
    chmod 0755, libexec/"dist/index.js"
    (bin/"listmonk").write <<~EOS
      #!/bin/bash
      exec "#{Formula["node"].opt_bin}/node" "#{libexec}/dist/index.js" "$@"
    EOS
  end

  test do
    system "#{bin}/listmonk", "--help"
  end
end
