# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Postflow < Formula
  desc "CLI for PostFlow publishing workflows."
  homepage "https://github.com/antoniolg/postflow"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/antoniolg/postflow/releases/download/v0.2.1/postflow_0.2.1_darwin_amd64.tar.gz"
      sha256 "551fe44d243ac485c950393090b2e9b3c378bbe69b55f9822d1b3350b6cd465c"

      def install
        bin.install "postflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/antoniolg/postflow/releases/download/v0.2.1/postflow_0.2.1_darwin_arm64.tar.gz"
      sha256 "eb4332694dcb967381d4e5a816d2dbbc8a3a5fc41b83d05df08b29243a50fd90"

      def install
        bin.install "postflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniolg/postflow/releases/download/v0.2.1/postflow_0.2.1_linux_amd64.tar.gz"
      sha256 "81c380240b92b037405d74c4d8744fe30314c8bff91e3945a2f798a10c0381be"

      def install
        bin.install "postflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniolg/postflow/releases/download/v0.2.1/postflow_0.2.1_linux_arm64.tar.gz"
      sha256 "bfd32727eae49e8057d5cc34e6357d4072079ed1a996b7659ad023619c9e9a1d"

      def install
        bin.install "postflow"
      end
    end
  end

  test do
    system "#{bin}/postflow", "--help"
  end
end
