# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Postflow < Formula
  desc "CLI for PostFlow publishing workflows."
  homepage "https://github.com/antoniolg/postflow"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/antoniolg/postflow/releases/download/v0.4.0/postflow_0.4.0_darwin_amd64.tar.gz"
      sha256 "7c6d7eb6a4a271f0c209c11cfbe2c4312fb4748367603999d0f3015929e04585"

      def install
        bin.install "postflow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/antoniolg/postflow/releases/download/v0.4.0/postflow_0.4.0_darwin_arm64.tar.gz"
      sha256 "9caf80856261b4be4f23ae0d2ab256a02aa54836e94b1ba00f55edb1163d9885"

      def install
        bin.install "postflow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniolg/postflow/releases/download/v0.4.0/postflow_0.4.0_linux_amd64.tar.gz"
      sha256 "3c9bb0432b75b41f32ad7828ae0388da89e95001ed3ac5c851f88353b9c8e1a8"

      def install
        bin.install "postflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniolg/postflow/releases/download/v0.4.0/postflow_0.4.0_linux_arm64.tar.gz"
      sha256 "4229f4edd59d7023ef0f9c86ffff4807b754206a1cc02c7f879585d37afe2ba9"

      def install
        bin.install "postflow"
      end
    end
  end

  test do
    system "#{bin}/postflow", "--help"
  end
end
