# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class PostflowCli < Formula
  desc "CLI for PostFlow publishing workflows."
  homepage "https://github.com/antoniolg/postflow"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/antoniolg/postflow/releases/download/v0.1.0/postflow-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "34a5cf9ebdb236430d86763ec9f797c401e4cbffb365ee3a0d06bc25872cba24"

      def install
        bin.install "publisher-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/antoniolg/postflow/releases/download/v0.1.0/postflow-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "94a8492f34524d3d624abc0f28adcb4494c4a8e740d185f5319315ebde1bc7f4"

      def install
        bin.install "publisher-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniolg/postflow/releases/download/v0.1.0/postflow-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "209c119214d8093ce932f61380d28508c8fae687305f2a38fa575cc38518e30a"

      def install
        bin.install "publisher-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/antoniolg/postflow/releases/download/v0.1.0/postflow-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "f24ed49e119068a5d2c321de07dc557323d70855ea1dc1311a8b1452c61583f4"

      def install
        bin.install "publisher-cli"
      end
    end
  end

  test do
    system "#{bin}/publisher-cli", "--help"
  end
end
